# Copyright (c) 2024 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: gh_adze
      url-base: https://github.com/AdamZelikNS

  projects:
    - name: nrf
      remote: gh_adze
      repo-path: sdk-nrf
      revision: tst/n54L_uid64_v1dbg
      import: true
